# Generated by Django 5.1.5 on 2025-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('weatherDescription', models.CharField(max_length=255)),
            ],
        ),
    ]
