# Generated by Django 5.1.5 on 2025-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAZAO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='willitraintommorow',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
